# Generated by Django 5.1.4 on 2024-12-18 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('about', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PU', 'Published'), ('PR', 'Private')], default='DF', max_length=10)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['-published'], name='create_reci_publish_3280c2_idx')],
            },
        ),
    ]
